#!/usr/bin/env python3
"""Find card interactions from what cards DO, not from what people play.

Every candidate here is generated by matching parsed oracle-text primitives
against loop templates. Popularity is never an input, so a pair that nobody has
ever put in a deck together scores exactly as well as a famous one.

Each candidate is then checked against the 110k known Commander Spellbook combos
and labelled `known` or `novel`. Novel means "not in that database" - it does not
mean the interaction is good, and it does not mean it works: the parser reads
text, it does not know the rules. Treat novel hits as leads to verify by hand.
"""
import json, re

WUBRG = "WUBRG"

# What an untap effect can legally point at.
#
# The target phrase is not a single type. "artifact creature" means the target
# must be BOTH - Voltaic Construct cannot untap Chromatic Orrery, which is an
# artifact but not a creature. "artifact or land" means either. And some targets
# carry a condition the combo can never satisfy: a mana dork that tapped for mana
# is not an attacking creature, so Najeela can never untap it.
TYPE_WORDS = {
    "artifact": "artifact", "artifacts": "artifact",
    "creature": "creature", "creatures": "creature",
    "land": "land", "lands": "land",
    "enchantment": "enchantment", "enchantments": "enchantment",
    "permanent": None, "permanents": None,        # any type at all
}

# Conditions on the target that an untap loop can't arrange.
IMPOSSIBLE_TARGET = re.compile(
    r"\battacking\b|\bblocking\b|\bblocked\b|"
    r"an opponent controls|you don't control|opponent's|"
    r"\bcreature token\b|\bthat attacked\b|\bthat was dealt\b", re.I)

# An aura or equipment untapping "enchanted"/"equipped" creature is fine - you
# attach it to the mana producer, which is exactly how those combos are built.
ATTACHED = re.compile(r"\benchanted\b|\bequipped\b", re.I)


def _target_options(target):
    """Target phrase -> list of required type-sets, any one of which satisfies it.

    An empty set inside the list means "any permanent". An empty LIST means the
    phrase names no permanent type we recognise, or carries a condition a loop
    can never meet - in both cases the untapper is unusable.
    """
    t = (target or "").strip().lower()
    if not t or t == "self":
        return []
    if IMPOSSIBLE_TARGET.search(t):
        return []
    options = []
    for alternative in re.split(r"\bor\b", t):
        required = set()
        matched = False
        for word in re.findall(r"[a-z']+", alternative):
            if word in TYPE_WORDS:
                matched = True
                kind = TYPE_WORDS[word]
                if kind:
                    required.add(kind)
        if matched:
            options.append(required)
    return options


def _scope_ok(target, source_types):
    """Can an untapper with this target phrase untap a permanent of these types?"""
    for required in _target_options(target):
        if required <= source_types:
            return True
    return False


def _types(type_line):
    tl = (type_line or "").lower()
    return {w for w in ("artifact", "creature", "land", "enchantment") if w in tl}


def _ci_ok(a, b, ci):
    """Both cards must fit inside the deck's colour identity, if one is given."""
    if not ci:
        return True
    allowed = set(ci.upper()) | {"C"}
    for s in (a or "C", b or "C"):
        if not set(s) <= allowed:
            return False
    return True


def _known_index(con):
    """oracle_id -> list of frozensets, each a known combo's full card set."""
    idx = {}
    for cid, key in con.execute("select id, card_key from combos where card_key != ''"):
        s = frozenset(key.split("|"))
        for o in s:
            idx.setdefault(o, []).append(s)
    return idx


def _is_known(idx, card_set):
    for o in card_set:
        for known in idx.get(o, ()):
            if known <= card_set:
                return True
    return False



def _mana_pays_for(produced, *costs):
    """Can mana of these colours pay every coloured pip in these costs?

    A loop has to fund itself. Canopy Tactician taps for {G}{G}{G} and Pemmin's
    Aura untaps for {U} - three green mana buys you nothing, so that is not a
    loop. Generic and colourless pips are payable by anything and are ignored.
    """
    from collections import Counter
    have = Counter(ch for ch in (produced or "") if ch != "C")
    need = Counter()
    for c in costs:
        need.update(ch for ch in (c or "") if ch != "C")
    return all(have[colour] >= n for colour, n in need.items())


def _card_rows(con, where="1", args=()):
    sql = """select c.oracle_id, c.name, c.type_line, c.cmc, c.price_usd, c.color_identity,
                    c.oracle_text, c.edh_decks, p.tcgplayer_id
             from cards c left join printings p on p.id = c.cheap_printing_id
             where %s""" % where
    return {r["oracle_id"]: dict(r) for r in con.execute(sql, args)}


def _prims(con, kinds):
    marks = ",".join("?" * len(kinds))
    out = {}
    for r in con.execute("select * from card_functions where kind in (%s)" % marks, list(kinds)):
        out.setdefault(r["kind"], []).append(dict(r))
    return out


def find(con, template="infinite_mana", ci=None, max_price=None, max_pair_price=None,
         novel_only=False, limit=60, min_edh_decks=None, payoffs=False):
    """Generate candidate interactions for one template."""
    kinds = {
        "infinite_mana": ("mana_add", "untap"),
        "sac_loop": ("sac_outlet", "self_recur"),
        "sac_drain": ("sac_outlet", "self_recur", "drain"),
        "blink_engine": ("blink", "etb_mana", "etb_untap_lands"),
        "cost_reduction_mana": ("mana_add", "untap", "cost_reduce_ability"),
    }.get(template)
    if not kinds:
        return {"error": "unknown template", "templates": ["infinite_mana", "sac_loop",
                                                           "sac_drain", "blink_engine"]}
    if not con.execute("select count(*) from sqlite_master where type='table' and name='card_functions'").fetchone()[0]:
        return {"error": "function layer not built - run build_functions.py"}

    # Vanguard, Plane, Scheme and friends are not cards you can put in a deck -
    # "Oracle" the Vanguard card was producing free untaps for every mana rock.
    where, args = ["c.oracle_text is not null",
                   "exists (select 1 from legalities l where l.oracle_id = c.oracle_id "
                   "and l.format='commander' and l.status in ('legal','restricted'))"], []
    if max_price is not None:
        where.append("c.price_usd is not null and c.price_usd <= ?")
        args.append(max_price)
    if min_edh_decks:
        where.append("coalesce(c.edh_decks,0) >= ?")
        args.append(min_edh_decks)
    cards = _card_rows(con, " and ".join(where), args)
    prims = _prims(con, kinds)
    idx = _known_index(con)
    out = []

    if template == "infinite_mana":
        # A taps for mana; B untaps A for less than A makes -> unbounded mana.
        # B must not tap itself to do it, or it cannot repeat; neither card may
        # sacrifice itself as part of the cost.
        sources = [p for p in prims.get("mana_add", [])
                   if p["taps"] and p["repeatable"] and not p["sac_self"]
                   and not p["finite_cost"] and not p["restricted"]
                   and (p["amount"] or 0) >= 2]
        untappers = [p for p in prims.get("untap", [])
                     if _target_options(p["detail"]) and p["repeatable"] and not p["taps"]
                     and not p["sac_self"] and not p["finite_cost"]
                     and (p["detail"] or "") != "self"]
        for a in sources:
            ca = cards.get(a["oracle_id"])
            if not ca:
                continue
            atypes = _types(ca["type_line"])
            for b in untappers:
                if b["oracle_id"] == a["oracle_id"]:
                    continue
                cb = cards.get(b["oracle_id"])
                if not cb or not _scope_ok(b["detail"], atypes):
                    continue
                # the source's own activation cost counts too: Crystal Quarry
                # pays {5} to make 5, so untapping it forever nets nothing
                cost = (b["cost_mana"] or 0) + (a["cost_mana"] or 0)
                surplus = (a["amount"] or 0) - cost
                if surplus <= 0 or not _ci_ok(ca["color_identity"], cb["color_identity"], ci):
                    continue
                # the mana produced has to be able to pay for the untap
                if not a["any_color"] and not _mana_pays_for(
                        a["colors"], b["cost_colors"], a["cost_colors"]):
                    continue
                # mana that can't pay generic costs can only fund an ability whose
                # cost is entirely coloured pips
                if a["no_generic"]:
                    pips = len(b["cost_colors"] or "") + len(a["cost_colors"] or "")
                    if cost > pips:
                        continue
                out.append(_cand([ca, cb], idx,
                                 "%s taps for %d%s; %s untaps it for %d — net +%d mana per loop"
                                 % (ca["name"], a["amount"],
                                    " {%s}" % a["colors"] if a["colors"] else "",
                                    cb["name"], cost, surplus),
                                 "infinite colorless/colored mana", surplus))

    elif template in ("sac_loop", "sac_drain"):
        outlets = [p for p in prims.get("sac_outlet", []) if p["free"] and p["detail"] == "creature"]
        # only recursion that can be used again and again closes the loop;
        # unearth/disturb/flashback bring a creature back exactly once
        # These are recursion ENGINES, not infinite loops: almost every repeatable
        # self-recursion costs mana per iteration, so the loop is bounded by your
        # mana. Cheapest loops first.
        # detail holds either "repeatable", "once", or the board-state condition
        recurs = [p for p in prims.get("self_recur", [])
                  if p["detail"] != "once" and p["repeatable"]
                  and (p["cost_mana"] or 0) <= 2]
        drains = [p for p in prims.get("drain", [])] if template == "sac_drain" else [None]
        recur_cards = [cards.get(p["oracle_id"]) for p in recurs]
        recur_cards = [c for c in recur_cards if c and "Creature" in (c["type_line"] or "")]
        for a in outlets:
            ca = cards.get(a["oracle_id"])
            if not ca:
                continue
            for cb in recur_cards:
                if cb["oracle_id"] == ca["oracle_id"]:
                    continue
                if not _ci_ok(ca["color_identity"], cb["color_identity"], ci):
                    continue
                rec = next(p for p in recurs if p["oracle_id"] == cb["oracle_id"])
                loop_cost = rec["cost_mana"] or 0
                # a board-state condition doesn't stop the engine, but it is part
                # of the deal and belongs in the description
                caveat = ""
                if (rec["detail"] or "").startswith(("as long as", "if you control")):
                    caveat = " — only %s" % rec["detail"]
                if template == "sac_loop":
                    out.append(_cand([ca, cb], idx,
                                     "%s sacrifices for free; %s returns itself for %d mana — "
                                     "repeatable death triggers at %d mana a loop%s"
                                     % (ca["name"], cb["name"], loop_cost, loop_cost, caveat),
                                     "repeatable (not infinite) death/ETB triggers",
                                     3 - loop_cost))
                else:
                    for d in drains:
                        cc = cards.get(d["oracle_id"])
                        if not cc or cc["oracle_id"] in (ca["oracle_id"], cb["oracle_id"]):
                            continue
                        if ci and not set(cc["color_identity"] or "C") <= (set(ci.upper()) | {"C"}):
                            continue
                        out.append(_cand([ca, cb, cc], idx,
                                         "%s sacrifices %s repeatedly; %s drains on each death"
                                         % (ca["name"], cb["name"], cc["name"]),
                                         "drain each opponent out", 1))

    elif template == "cost_reduction_mana":
        # A rock that taps for N but untaps itself for more than N is useless alone.
        # Something that makes activated abilities cheaper flips it positive -
        # this is the Basalt Monolith + Zirda shape, and the cube found it first.
        by_card = {}
        for pr in prims.get("mana_add", []) + prims.get("untap", []):
            by_card.setdefault(pr["oracle_id"], []).append(pr)
        # the reduction has to cover the rock's own card type
        reducers = [pr for pr in prims.get("cost_reduce_ability", [])
                    if (pr["amount"] or 0) >= 1 and pr["detail"] != "narrow"]
        for oid, plist in by_card.items():
            ca = cards.get(oid)
            if not ca:
                continue
            mana = [pr for pr in plist if pr["kind"] == "mana_add" and pr["taps"]
                    and pr["repeatable"] and not pr["sac_self"] and not pr["finite_cost"]
                    and not pr["restricted"]]
            selfuntap = [pr for pr in plist if pr["kind"] == "untap"
                         and (pr["detail"] or "") == "self" and pr["repeatable"]
                         and not pr["finite_cost"]]
            # the rock has to be able to pay its own untap cost out of what it makes
            mana = [m for m in mana
                    if (m["any_color"] or any(
                        _mana_pays_for(m["colors"], u["cost_colors"], m["cost_colors"])
                        for u in selfuntap))
                    and not m["no_generic"]        # self-untaps are generic in practice
                    ] if selfuntap else []
            if not mana or not selfuntap:
                continue
            best_mana = max(m["amount"] or 0 for m in mana)
            cheapest = min(u["cost_mana"] or 0 for u in selfuntap)
            gap = cheapest - best_mana           # what the reducer has to cover
            atypes = _types(ca["type_line"])
            for rd in reducers:
                cb = cards.get(rd["oracle_id"])
                if not cb or cb["oracle_id"] == oid:
                    continue
                if rd["detail"] != "permanent" and rd["detail"] not in atypes:
                    continue                      # wrong card type for this reducer
                # several reducers can't take a cost below one mana
                eff = (rd["amount"] or 0)
                if rd["free"]:
                    eff = min(eff, max(0, cheapest - 1))
                if eff <= gap:
                    continue                      # not enough of a discount
                if not _ci_ok(ca["color_identity"], cb["color_identity"], ci):
                    continue
                surplus = best_mana - max(0, cheapest - eff)
                out.append(_cand([ca, cb], idx,
                                 "%s taps for %d and untaps itself for %d; %s makes that "
                                 "%d cheaper — net +%d mana per loop"
                                 % (ca["name"], best_mana, cheapest, cb["name"],
                                    eff, surplus),
                                 "infinite colorless mana", surplus))

    elif template == "blink_engine":
        # A card that only exiles ITSELF cannot flicker a separate payload card, so
        # it can't be half of a two-card loop however cheap its ability is.
        blinkers = [p for p in prims.get("blink", []) if (p["cost_mana"] or 0) >= 0
                    and p["repeatable"] and not p["taps"] and not p["sac_self"]
                    and not p["finite_cost"] and (p["detail"] or "self") != "self"]
        payload = _prims(con, ("etb_mana", "etb_untap_lands"))
        etbs = payload.get("etb_mana", []) + payload.get("etb_untap_lands", [])
        mana_by_card = {p["oracle_id"]: (p["amount"] or 0)
                        for p in payload.get("etb_mana", []) if p["repeatable"]}
        untap_lands = {p["oracle_id"]: (p["amount"] or 1)
                       for p in payload.get("etb_untap_lands", []) if p["repeatable"]}
        for a in blinkers:
            ca = cards.get(a["oracle_id"])
            if not ca:
                continue
            cost = a["cost_mana"] or 0
            for b in etbs:
                if b["oracle_id"] == a["oracle_id"]:
                    continue
                cb = cards.get(b["oracle_id"])
                if not cb or not _ci_ok(ca["color_identity"], cb["color_identity"], ci):
                    continue
                # and the payload has to be something this blinker can target
                if not _scope_ok(a["detail"], _types(cb["type_line"])):
                    continue
                gain = mana_by_card.get(cb["oracle_id"], 0)
                lands = untap_lands.get(cb["oracle_id"], 0)
                # the loop only runs if the enter trigger pays for the next blink
                if max(gain, lands) <= cost:
                    continue
                out.append(_cand([ca, cb], idx,
                                 "%s blinks for %d; %s's enter trigger %s"
                                 % (ca["name"], cost, cb["name"],
                                    ("untaps %s lands" % ("all" if lands >= 99 else lands))
                                    if lands else "makes %d mana" % gain),
                                 "infinite blink / ETB triggers", max(gain, lands) - cost))

    if max_pair_price is not None:
        out = [c for c in out if c["total_price"] is not None and c["total_price"] <= max_pair_price]
    # measure the rediscovery rate over ALL candidates, before the novel filter -
    # hiding the known ones must not make the template look like it found nothing
    total_n = len(out)
    known_n = sum(1 for c in out if not c["novel"])
    if novel_only:
        out = [c for c in out if c["novel"]]
    out.sort(key=lambda c: (-c["strength"], c["total_price"] if c["total_price"] is not None else 1e9))
    bounded = template in BOUNDED
    result = {"template": template, "candidates": out[:limit], "generated": total_n,
            "shown": len(out),
            "novel": total_n - known_n,
            "known": known_n,
            # a rediscovery rate only means something for templates that claim to
            # find infinite combos
            "known_rate": None if bounded else round(100.0 * known_n / max(total_n, 1), 1),
            "bounded": bounded,
            "reliability": RELIABILITY.get(template, "unmeasured")}
    if payoffs:
        # `out` is every engine found; result["candidates"] is only the page
        three = with_payoffs(con, out, template, ci=ci,
                             max_price=max_price, limit=limit)
        result["three_card"] = three["candidates"]
        result["three_card_total"] = three["generated"]
        result["three_card_known"] = three["known"]
        result["three_card_rate"] = three["known_rate"]
    return result


# Measured by how often a template's candidates turn out to be combos Commander
# Spellbook already lists. High is good: it means the template's logic matches how
# real combos are built, so its NOVEL hits are worth looking at.
# Templates that find BOUNDED engines rather than infinite loops. Measuring these
# against a database of infinite combos is meaningless - they are not trying to be
# combos - so they report no rate rather than a misleading 0%.
BOUNDED = {"sac_loop", "sac_drain"}

RELIABILITY = {
    "blink_engine": "good - about half its candidates are already-known combos",
    "infinite_mana": "fair - finds real untap loops, but restricted-mana cards "
                     "(Jegantha) and targeting rules still slip through",
    "cost_reduction_mana": "good - narrow by construction; rediscovers the "
                           "Basalt Monolith + Zirda family",
    "sac_loop": "not a combo finder - these are repeatable value engines that cost "
                "mana every loop, so they will never appear in a database of infinite "
                "combos. Judge them on the per-loop cost, not on a rediscovery rate.",
    "sac_drain": "same as sac_loop: a bounded drain engine, not an infinite combo",
}



# ───────────────────────────── payoffs ─────────────────────────────
#
# A loop on its own doesn't win the game. The known-combo database is mostly 3-
# and 4-card entries for exactly this reason: two cards make the engine, a third
# turns it into a kill. These queries find that third card.

PAYOFF_SQL = {
    # infinite mana -> something to pour it into
    "mana": """
        select c.oracle_id, c.name, c.type_line, c.color_identity, c.price_usd,
               c.edh_decks, p.tcgplayer_id, c.oracle_text
        from cards c left join printings p on p.id = c.cheap_printing_id
        where (c.mana_cost like '%{X}%' or c.oracle_text like '%X target%'
               or c.oracle_text like '%equal to the amount of mana%')
          and (c.oracle_text like '%deals X damage%'
               or c.oracle_text like '%draw X card%'
               or c.oracle_text like '%loses X life%')
          and exists (select 1 from legalities l where l.oracle_id = c.oracle_id
                      and l.format='commander' and l.status='legal')
        order by c.edh_decks desc nulls last limit 60""",
    # infinite enter/leave triggers -> something that drains on each one
    "etb": """
        select c.oracle_id, c.name, c.type_line, c.color_identity, c.price_usd,
               c.edh_decks, p.tcgplayer_id, c.oracle_text
        from cards c
        join card_functions f on f.oracle_id = c.oracle_id and f.kind = 'drain'
        left join printings p on p.id = c.cheap_printing_id
        where (c.oracle_text like '%Whenever%dies%' or c.oracle_text like '%Whenever%enters%')
          and exists (select 1 from legalities l where l.oracle_id = c.oracle_id
                      and l.format='commander' and l.status='legal')
        order by c.edh_decks desc nulls last limit 60""",
}

PAYOFF_KIND = {"infinite_mana": "mana", "cost_reduction_mana": "mana",
               "blink_engine": "etb", "sac_loop": "etb", "sac_drain": "etb"}


def _payoffs(con, kind, max_price=None):
    rows = [dict(r) for r in con.execute(PAYOFF_SQL[kind])]
    if max_price is not None:
        rows = [r for r in rows if r["price_usd"] is not None and r["price_usd"] <= max_price]
    return rows


def with_payoffs(con, engines, template, ci=None, max_price=None, limit=60):
    """Turn two-card engines into three-card kills by attaching a payoff.

    Returns a NEW candidate list; the engine candidates are left untouched so you
    can still see the loop on its own.
    """
    kind = PAYOFF_KIND.get(template)
    if not kind or not engines:
        return {"candidates": [], "generated": 0, "known": 0, "known_rate": None}
    pays = _payoffs(con, kind, max_price)
    if not pays:
        return {"candidates": [], "generated": 0, "known": 0, "known_rate": None}
    idx = _known_index(con)
    out = []
    for cand in engines:
        engine_ids = {c["oracle_id"] for c in cand["cards"]}
        engine_ci = set("".join(c["color_identity"] or "" for c in cand["cards"]))
        for pay in pays:
            if pay["oracle_id"] in engine_ids:
                continue
            pci = set(pay["color_identity"] or "")
            if ci and not pci <= (set(ci.upper()) | {"C"}):
                continue
            # a three-card combo has to sit inside ONE deck's colours
            if len(engine_ci | pci - {"C"}) > 5:
                continue
            cards_ = cand["cards"] + [{
                "name": pay["name"], "oracle_id": pay["oracle_id"],
                "price_usd": pay["price_usd"], "type_line": pay["type_line"],
                "color_identity": pay["color_identity"], "edh_decks": pay["edh_decks"],
                "tcgplayer_id": pay["tcgplayer_id"]}]
            key = frozenset(c["oracle_id"] for c in cards_)
            prices = [c["price_usd"] for c in cards_]
            out.append({
                "cards": cards_,
                "why": cand["why"] + "; %s converts that into a win" % pay["name"],
                "produces": cand["produces"] + " → win",
                "strength": cand["strength"],
                "total_price": round(sum(x for x in prices if x is not None), 2)
                               if all(x is not None for x in prices) else None,
                "novel": not _is_known(idx, key),
                "played_together_hint": min((c["edh_decks"] or 0) for c in cards_),
                "pieces": len(cards_),
            })
    # measure BEFORE truncating: the sort puts known combos first, so a rate taken
    # from the returned slice would read 100% however bad the generator is
    total_n = len(out)
    known_n = sum(1 for c in out if not c["novel"])
    out.sort(key=lambda c: (c["novel"], c["total_price"] if c["total_price"] is not None else 1e9))
    return {"candidates": out[:limit], "generated": total_n, "known": known_n,
            "known_rate": round(100.0 * known_n / max(total_n, 1), 1)}

def _cand(cards_, idx, why, produces, strength):
    key = frozenset(c["oracle_id"] for c in cards_)
    prices = [c["price_usd"] for c in cards_]
    return {
        "cards": [{"name": c["name"], "oracle_id": c["oracle_id"], "price_usd": c["price_usd"],
                   "type_line": c["type_line"], "color_identity": c["color_identity"],
                   "edh_decks": c["edh_decks"], "tcgplayer_id": c["tcgplayer_id"]} for c in cards_],
        "why": why, "produces": produces, "strength": strength,
        "total_price": round(sum(p for p in prices if p is not None), 2) if all(
            p is not None for p in prices) else None,
        "novel": not _is_known(idx, key),
        "played_together_hint": min((c["edh_decks"] or 0) for c in cards_),
    }
